"""
Hardcoded lookup data for scaffold generation.
Thinker bios, text metadata, German terms, tradition assignments.
"""

# --- Thinker biographical data ---
# name -> {born, died, nationality, tradition, key_works, tags}
THINKER_DATA = {
    "Pierre-Joseph Proudhon": {"born": 1809, "died": 1865, "nationality": "French", "tradition": "Utopian Socialism", "key_works": ["What Is Property?", "The Philosophy of Poverty"], "tags": ["anarchism", "mutualism", "property"]},
    "Karl Grün": {"born": 1817, "died": 1887, "nationality": "German", "tradition": "True Socialism", "key_works": ["The Social Movement in France and Belgium"], "tags": ["true socialism", "Young Hegelians"]},
    "Wilhelm Weitling": {"born": 1808, "died": 1871, "nationality": "German", "tradition": "Utopian Socialism", "key_works": ["Guarantees of Harmony and Freedom"], "tags": ["utopian socialism", "workers movement"]},
    "Feargus O'Connor": {"born": 1796, "died": 1855, "nationality": "Irish", "tradition": "Chartism", "key_works": ["The Northern Star"], "tags": ["Chartism", "land reform"]},
    "François Guizot": {"born": 1787, "died": 1874, "nationality": "French", "tradition": "Liberal Conservatism", "key_works": ["History of Civilization in Europe"], "tags": ["liberalism", "class struggle", "historiography"]},
    "Louis Blanc": {"born": 1811, "died": 1882, "nationality": "French", "tradition": "State Socialism", "key_works": ["The Organization of Work"], "tags": ["state socialism", "cooperatives"]},
    "Alphonse de Lamartine": {"born": 1790, "died": 1869, "nationality": "French", "tradition": "Romantic Republicanism", "key_works": ["History of the Girondins"], "tags": ["republicanism", "1848 revolution"]},
    "Adolphe Bartels": {"born": 1802, "died": 1862, "nationality": "Belgian", "tradition": "Democratic Radicalism", "key_works": [], "tags": ["Belgian politics", "democratic movement"]},
    "Ledru-Rollin": {"born": 1807, "died": 1874, "nationality": "French", "tradition": "Democratic Republicanism", "key_works": ["De la Décadence de l'Angleterre"], "tags": ["republicanism", "1848 revolution", "democratic movement"]},
    "Flocon": {"born": 1800, "died": 1866, "nationality": "French", "tradition": "Democratic Republicanism", "key_works": [], "tags": ["1848 revolution", "journalism", "democratic movement"]},
    "Karl Beck": {"born": 1817, "died": 1879, "nationality": "Hungarian-German", "tradition": "Young Germany", "key_works": ["Songs of the Poor Man"], "tags": ["poetry", "social criticism"]},
    "Arnold Ruge": {"born": 1802, "died": 1880, "nationality": "German", "tradition": "Left Hegelianism", "key_works": ["German-French Yearbooks"], "tags": ["Young Hegelians", "democratic movement"]},
    "Joseph Stalin": {"born": 1878, "died": 1953, "nationality": "Georgian-Soviet", "tradition": "Marxism-Leninism", "key_works": ["Dialectical and Historical Materialism", "The Foundations of Leninism", "The National Question"], "tags": ["Marxism-Leninism", "state socialism", "national question"]},
    "Ernst Bloch": {"born": 1885, "died": 1977, "nationality": "German", "tradition": "Western Marxism", "key_works": ["The Principle of Hope", "The Spirit of Utopia"], "tags": ["utopia", "hope", "ontology"]},
    "Lucien Goldmann": {"born": 1913, "died": 1970, "nationality": "Romanian-French", "tradition": "Western Marxism", "key_works": ["The Hidden God", "Towards a Sociology of the Novel"], "tags": ["genetic structuralism", "literature", "consciousness"]},
    "Henri Lefebvre": {"born": 1901, "died": 1991, "nationality": "French", "tradition": "Western Marxism", "key_works": ["The Production of Space", "Critique of Everyday Life"], "tags": ["space", "everyday life", "urbanization"]},
    "Ralph Miliband": {"born": 1924, "died": 1994, "nationality": "Belgian-British", "tradition": "British Marxism", "key_works": ["The State in Capitalist Society", "Marxism and Politics"], "tags": ["state theory", "political sociology"]},
    "Immanuel Wallerstein": {"born": 1930, "died": 2019, "nationality": "American", "tradition": "World-Systems Theory", "key_works": ["The Modern World-System", "Historical Capitalism"], "tags": ["world-systems", "capitalism", "longue durée"]},
    "Giovanni Arrighi": {"born": 1937, "died": 2009, "nationality": "Italian", "tradition": "World-Systems Theory", "key_works": ["The Long Twentieth Century", "Adam Smith in Beijing"], "tags": ["world-systems", "accumulation cycles", "hegemony"]},
    "Erik Olin Wright": {"born": 1947, "died": 2019, "nationality": "American", "tradition": "Analytical Marxism", "key_works": ["Classes", "Envisioning Real Utopias"], "tags": ["class analysis", "analytical Marxism", "utopias"]},
    "G. A. Cohen": {"born": 1941, "died": 2009, "nationality": "Canadian-British", "tradition": "Analytical Marxism", "key_works": ["Karl Marx's Theory of History: A Defence"], "tags": ["analytical Marxism", "historical materialism", "philosophy"]},
    "Ellen Meiksins Wood": {"born": 1942, "died": 2016, "nationality": "American-Canadian", "tradition": "Political Marxism", "key_works": ["The Origin of Capitalism", "Democracy Against Capitalism"], "tags": ["political Marxism", "capitalism origins", "democracy"]},
    "Robert Brenner": {"born": 1943, "died": None, "nationality": "American", "tradition": "Political Marxism", "key_works": ["The Economics of Global Turbulence", "Merchants and Revolution"], "tags": ["political Marxism", "agrarian capitalism", "crisis theory"]},
    "Harry Braverman": {"born": 1920, "died": 1976, "nationality": "American", "tradition": "Monthly Review School", "key_works": ["Labor and Monopoly Capital"], "tags": ["labor process", "deskilling", "monopoly capitalism"]},
    "Paul Baran": {"born": 1909, "died": 1964, "nationality": "Russian-American", "tradition": "Monthly Review School", "key_works": ["The Political Economy of Growth", "Monopoly Capital"], "tags": ["underdevelopment", "monopoly capitalism", "surplus"]},
    "André Gunder Frank": {"born": 1929, "died": 2005, "nationality": "German-American", "tradition": "Dependency Theory", "key_works": ["Capitalism and Underdevelopment in Latin America", "ReOrient"], "tags": ["dependency theory", "underdevelopment", "world-systems"]},
    "Maurice Dobb": {"born": 1900, "died": 1976, "nationality": "British", "tradition": "British Marxism", "key_works": ["Studies in the Development of Capitalism", "Theories of Value and Distribution"], "tags": ["economic history", "transition debate", "value theory"]},
    "Christopher Hill": {"born": 1912, "died": 2003, "nationality": "British", "tradition": "British Marxism", "key_works": ["The World Turned Upside Down", "The English Revolution 1640"], "tags": ["English revolution", "history from below", "radicalism"]},
    "Eric Hobsbawm": {"born": 1917, "died": 2012, "nationality": "British", "tradition": "British Marxism", "key_works": ["The Age of Revolution", "The Age of Capital", "The Age of Empire", "The Age of Extremes"], "tags": ["historiography", "nationalism", "social history"]},
    "Perry Anderson": {"born": 1938, "died": None, "nationality": "British", "tradition": "Western Marxism", "key_works": ["Lineages of the Absolutist State", "Considerations on Western Marxism", "The New Old World"], "tags": ["state theory", "Western Marxism", "historiography"]},
    "Raymond Williams": {"born": 1921, "died": 1988, "nationality": "Welsh", "tradition": "British Marxism", "key_works": ["Culture and Society", "The Long Revolution", "Marxism and Literature"], "tags": ["cultural materialism", "literature", "culture"]},
    "Stuart Hall": {"born": 1932, "died": 2014, "nationality": "Jamaican-British", "tradition": "British Marxism", "key_works": ["Policing the Crisis", "The Hard Road to Renewal"], "tags": ["cultural studies", "race", "hegemony", "Thatcherism"]},
    "István Mészáros": {"born": 1930, "died": 2017, "nationality": "Hungarian-British", "tradition": "Western Marxism", "key_works": ["Beyond Capital", "Marx's Theory of Alienation"], "tags": ["alienation", "capital system", "transition"]},
    "Michael Löwy": {"born": 1938, "died": None, "nationality": "Brazilian-French", "tradition": "Western Marxism", "key_works": ["The Theory of Revolution in the Young Marx", "Fire Alarm"], "tags": ["romanticism", "revolution", "ecology"]},
    "Che Guevara": {"born": 1928, "died": 1967, "nationality": "Argentine-Cuban", "tradition": "Revolutionary Marxism", "key_works": ["Guerrilla Warfare", "Man and Socialism in Cuba"], "tags": ["guerrilla warfare", "revolution", "new man"]},
    "Ho Chi Minh": {"born": 1890, "died": 1969, "nationality": "Vietnamese", "tradition": "Marxism-Leninism", "key_works": ["The Path Which Led Me to Leninism"], "tags": ["national liberation", "anti-colonialism", "revolution"]},
    "Deng Xiaoping": {"born": 1904, "died": 1997, "nationality": "Chinese", "tradition": "Marxism-Leninism", "key_works": ["Selected Works of Deng Xiaoping"], "tags": ["market socialism", "reform", "modernization"]},
    "Michael Hardt": {"born": 1960, "died": None, "nationality": "American", "tradition": "Autonomism", "key_works": ["Empire", "Multitude", "Commonwealth"], "tags": ["empire", "multitude", "biopolitics"]},
    "Bertell Ollman": {"born": 1935, "died": None, "nationality": "American", "tradition": "Western Marxism", "key_works": ["Alienation", "Dance of the Dialectic"], "tags": ["dialectics", "alienation", "internal relations"]},
    "Roman Rosdolsky": {"born": 1898, "died": 1967, "nationality": "Ukrainian", "tradition": "Classical Marxism", "key_works": ["The Making of Marx's Capital"], "tags": ["Grundrisse", "value theory", "methodology"]},
    "Henryk Grossman": {"born": 1881, "died": 1950, "nationality": "Polish", "tradition": "Classical Marxism", "key_works": ["The Law of Accumulation and Breakdown of the Capitalist System"], "tags": ["crisis theory", "breakdown", "accumulation"]},
    "Raya Dunayevskaya": {"born": 1910, "died": 1987, "nationality": "Ukrainian-American", "tradition": "Marxist-Humanism", "key_works": ["Marxism and Freedom", "Philosophy and Revolution"], "tags": ["humanism", "dialectics", "state capitalism"]},
    "Cornelius Castoriadis": {"born": 1922, "died": 1997, "nationality": "Greek-French", "tradition": "Autonomism", "key_works": ["The Imaginary Institution of Society"], "tags": ["autonomy", "imagination", "bureaucracy critique"]},
    "Daniel Bensaïd": {"born": 1946, "died": 2010, "nationality": "French", "tradition": "Trotskyism", "key_works": ["Marx for Our Times", "An Impatient Life"], "tags": ["strategy", "temporality", "revolution"]},
    "Adam Smith": {"born": 1723, "died": 1790, "nationality": "Scottish", "tradition": "Classical Political Economy", "key_works": ["The Wealth of Nations", "The Theory of Moral Sentiments"], "tags": ["political economy", "division of labor", "free trade"]},
    "Thomas Malthus": {"born": 1766, "died": 1834, "nationality": "British", "tradition": "Classical Political Economy", "key_works": ["An Essay on the Principle of Population"], "tags": ["population", "political economy", "scarcity"]},
    "Jean-Baptiste Say": {"born": 1767, "died": 1832, "nationality": "French", "tradition": "Classical Political Economy", "key_works": ["A Treatise on Political Economy"], "tags": ["Say's Law", "political economy"]},
    "James Mill": {"born": 1773, "died": 1836, "nationality": "Scottish", "tradition": "Classical Political Economy", "key_works": ["Elements of Political Economy"], "tags": ["political economy", "utilitarianism"]},
    "John Stuart Mill": {"born": 1806, "died": 1873, "nationality": "British", "tradition": "Classical Political Economy", "key_works": ["Principles of Political Economy", "On Liberty"], "tags": ["political economy", "liberalism", "utilitarianism"]},
    "William Petty": {"born": 1623, "died": 1687, "nationality": "English", "tradition": "Pre-Classical Political Economy", "key_works": ["Treatise of Taxes and Contributions"], "tags": ["political arithmetic", "labor theory of value"]},
    "François Quesnay": {"born": 1694, "died": 1774, "nationality": "French", "tradition": "Physiocracy", "key_works": ["Tableau Économique"], "tags": ["physiocracy", "economic table", "surplus"]},
    "Anne Robert Jacques Turgot": {"born": 1727, "died": 1781, "nationality": "French", "tradition": "Physiocracy", "key_works": ["Reflections on the Formation and Distribution of Wealth"], "tags": ["physiocracy", "political economy", "reform"]},
    "Claude Henri de Saint-Simon": {"born": 1760, "died": 1825, "nationality": "French", "tradition": "Utopian Socialism", "key_works": ["The Industrial System", "New Christianity"], "tags": ["utopian socialism", "industrialism", "technocracy"]},
    "Charles Fourier": {"born": 1772, "died": 1837, "nationality": "French", "tradition": "Utopian Socialism", "key_works": ["The Theory of the Four Movements"], "tags": ["utopian socialism", "phalansteries", "passions"]},
    "Robert Owen": {"born": 1771, "died": 1858, "nationality": "Welsh", "tradition": "Utopian Socialism", "key_works": ["A New View of Society"], "tags": ["utopian socialism", "cooperatives", "factory reform"]},
    "Étienne Cabet": {"born": 1788, "died": 1856, "nationality": "French", "tradition": "Utopian Socialism", "key_works": ["Voyage to Icaria"], "tags": ["utopian socialism", "communism", "utopian communities"]},
    "Pierre Leroux": {"born": 1797, "died": 1871, "nationality": "French", "tradition": "Romantic Socialism", "key_works": ["On Humanity"], "tags": ["socialism", "religion", "humanity"]},
    "Gracchus Babeuf": {"born": 1760, "died": 1797, "nationality": "French", "tradition": "Proto-Communism", "key_works": ["Manifesto of the Equals"], "tags": ["communism", "equality", "conspiracy"]},
    "Filippo Buonarroti": {"born": 1761, "died": 1837, "nationality": "Italian-French", "tradition": "Proto-Communism", "key_works": ["Babeuf's Conspiracy for Equality"], "tags": ["communism", "conspiracy", "revolution"]},
}

# --- Text metadata ---
TEXT_DATA = {
    "The Holy Family": {"author": "Karl Marx and Friedrich Engels", "year": 1845, "tradition": "Classical Marxism", "translations": ["Dixon (1956)"], "tags": ["critique", "Young Hegelians", "materialism"]},
    "Theories of Surplus Value": {"author": "Karl Marx", "year": 1863, "tradition": "Classical Marxism", "translations": ["Bonner and Burns (Lawrence & Wishart, 3 vols)"], "tags": ["surplus value", "political economy", "history of economic thought"]},
    "Critique of the Gotha Programme": {"author": "Karl Marx", "year": 1875, "tradition": "Classical Marxism", "translations": ["Various editions"], "tags": ["transition", "state", "distribution", "labor"]},
    "Critique of the Hegelian Philosophy of Right": {"author": "Karl Marx", "year": 1843, "tradition": "Classical Marxism", "translations": ["O'Malley (Cambridge 1970)"], "tags": ["state theory", "civil society", "Hegel critique"]},
    "Economic and Philosophic Manuscripts": {"author": "Karl Marx", "year": 1844, "tradition": "Classical Marxism", "translations": ["Milligan (1959)", "Livingstone and Benton (Penguin 1975)"], "tags": ["alienation", "labor", "humanism", "early Marx"]},
    "The Civil War in France": {"author": "Karl Marx", "year": 1871, "tradition": "Classical Marxism", "translations": ["Various editions"], "tags": ["Paris Commune", "state", "workers power"]},
    "Anti-Dühring": {"author": "Friedrich Engels", "year": 1878, "tradition": "Classical Marxism", "translations": ["Burns (International Publishers 1939)"], "tags": ["dialectics", "political economy", "scientific socialism"]},
    "Dialectics of Nature": {"author": "Friedrich Engels", "year": 1883, "tradition": "Classical Marxism", "translations": ["Dutt (International Publishers 1940)"], "tags": ["dialectics", "natural science", "materialism"]},
    "Socialism: Utopian and Scientific": {"author": "Friedrich Engels", "year": 1880, "tradition": "Classical Marxism", "translations": ["Aveling (1892)"], "tags": ["utopian socialism", "scientific socialism", "historical materialism"]},
    "Monopoly Capital": {"author": "Paul Baran and Paul Sweezy", "year": 1966, "tradition": "Monthly Review School", "translations": ["Monthly Review Press (1966)"], "tags": ["monopoly capitalism", "surplus", "stagnation"]},
    "Labor and Monopoly Capital": {"author": "Harry Braverman", "year": 1974, "tradition": "Monthly Review School", "translations": ["Monthly Review Press (1974, 1998 25th anniversary)"], "tags": ["labor process", "deskilling", "monopoly capitalism"]},
}

# --- German equivalents for common terms ---
GERMAN_TERMS = {
    "dialectical materialism": "Dialektischer Materialismus",
    "exploitation": "Ausbeutung",
    "wage labour": "Lohnarbeit",
    "proletariat": "Proletariat",
    "bourgeoisie": "Bourgeoisie",
    "petty bourgeoisie": "Kleinbürgertum",
    "social formation": "Gesellschaftsformation",
    "scientific socialism": "Wissenschaftlicher Sozialismus",
    "utopian socialism": "Utopischer Sozialismus",
    "communism": "Kommunismus",
    "socialism": "Sozialismus",
    "division of labour": "Teilung der Arbeit",
    "machinery": "Maschinerie",
    "industrial capital": "Industrielles Kapital",
    "merchant capital": "Kaufmannskapital",
    "finance capital": "Finanzkapital",
    "competition": "Konkurrenz",
    "monopoly": "Monopol",
    "overproduction": "Überproduktion",
    "absolutism": "Absolutismus",
    "proletarian revolution": "Proletarische Revolution",
    "trade unions": "Gewerkschaften",
    "class analysis": "Klassenanalyse",
    "capital dynamics": "Kapitaldynamik",
    "state theory": "Staatstheorie",
    "crisis theory": "Krisentheorie",
    "labour process": "Arbeitsprozess",
    "rent theory": "Rententheorie",
    "property relations": "Eigentumsverhältnisse",
    "wage system": "Lohnsystem",
    "monetary system": "Geldsystem",
    "agrarian question": "Agrarfrage",
    "emancipation": "Emanzipation",
    "dialectics method": "Dialektische Methode",
}

# --- Source citations for common terms ---
TERM_SOURCES = {
    "dialectical materialism": "Anti-Dühring; Dialectics of Nature",
    "exploitation": "Capital Vol. 1, Chs. 7-9",
    "wage labour": "Wage-Labour and Capital (1849)",
    "proletariat": "The Communist Manifesto",
    "bourgeoisie": "The Communist Manifesto",
    "petty bourgeoisie": "The Eighteenth Brumaire",
    "social formation": "Preface to A Contribution to the Critique of Political Economy",
    "scientific socialism": "Socialism: Utopian and Scientific",
    "utopian socialism": "Socialism: Utopian and Scientific",
    "communism": "The Communist Manifesto; The German Ideology",
    "socialism": "Critique of the Gotha Programme",
    "division of labour": "Capital Vol. 1, Chs. 14-15; The German Ideology",
    "machinery": "Capital Vol. 1, Ch. 15",
    "industrial capital": "Capital Vol. 2",
    "merchant capital": "Capital Vol. 3, Part IV",
    "finance capital": "Finance Capital (Hilferding, 1910)",
    "competition": "Capital Vol. 3; Grundrisse",
    "monopoly": "Capital Vol. 1, Ch. 25; Imperialism (Lenin)",
    "overproduction": "Capital Vol. 2-3; Theories of Surplus Value",
    "absolutism": "The Communist Manifesto; The Eighteenth Brumaire",
    "proletarian revolution": "The Communist Manifesto; State and Revolution",
    "trade unions": "Capital Vol. 1; Wages, Price and Profit",
    "Paris Commune": "The Civil War in France (1871)",
    "October Revolution": "History of the Russian Revolution (Trotsky)",
}
